sonar.projectKey=todo
sonar.projectName=todo
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000